# Setup
name: Beerstrap
description: Beerstrap. Startup project designed to ease and accelerate software development.
keywords: Beerstrap, startup project, prototype, agile, lean, development, framework, mockups, Grails, Java, HTML5, frontend, backend.
author:
  name:   Ra√∫l Gomis
  url:    https://twitter.com/rgomis
  email:  raulgomis@gmail.com
baseurl:  //raulgomis.github.io/beerstrap/

# Dependencies
markdown: redcarpet
highlighter: pygments

# Custom vars
version:  0.2
github:   https://github.com/raulgomis/beerstrap
demo:     http://beerstrap.rgomis.eu.cloudbees.net/
